const STORE='giaPhaViet.v2';
const WORKSPACES_STORE='giaPhaViet.workspaces.v1';
const ACTIVE_WORKSPACE_STORE='giaPhaViet.activeWorkspace.v1';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||'id-'+Date.now()+'-'+Math.random().toString(16).slice(2);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const year=d=>d?String(d).slice(0,4):'—';
const initials=n=>String(n||'?').trim().split(/\s+/).slice(-2).map(x=>x[0]).join('').toUpperCase();
const download=(name,text,type='application/json')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};

function emptyDb(){return {version:2,clan:{name:'Gia phả dòng họ',origin:'',founderId:'',history:'',compiler:'',lineageMode:'patrilineal'},branches:[],persons:[],families:[],media:[],events:[],updatedAt:new Date().toISOString()}}
function seed(){
  const branches=[
    {id:'b1',name:'Chi Trưởng',code:'C01',founderId:'p1',place:'Nam Định',description:'Nhánh trưởng, gìn giữ từ đường và gia phả gốc.'},
    {id:'b2',name:'Chi Thứ Hai',code:'C02',founderId:'p6',place:'Hà Nội',description:'Khai chi từ đời thứ ba, hiện sinh sống tại Hà Nội.'},
    {id:'b3',name:'Chi Phương Nam',code:'C03',founderId:'p12',place:'TP. Hồ Chí Minh',description:'Nhánh di cư vào phương Nam từ đầu thế kỷ XX.'}
  ];
  const raw=[
    ['p1','Nguyễn Văn Khởi','male','1832-04-08','1901-10-12',null,null,'b1','lineage','Nông học, khai canh'],
    ['p2','Trần Thị An','female','1838-02-10','1910-06-22',null,null,'b1','spouse','Nội trợ'],
    ['p3','Nguyễn Văn Phúc','male','1858-08-18','1934-03-11','p1','p2','b1','lineage','Thầy đồ'],
    ['p4','Nguyễn Thị Lành','female','1861-01-20','1939-05-03','p1','p2','b1','clan','Dệt vải'],
    ['p5','Lê Thị Dung','female','1863-09-01','1940-09-19',null,null,'b1','spouse',''],
    ['p6','Nguyễn Văn Thành','male','1885-06-14','1962-11-09','p3','p5','b2','lineage','Y sĩ'],
    ['p7','Nguyễn Văn Đức','male','1888-12-07','1968-02-17','p3','p5','b1','lineage','Nông nghiệp'],
    ['p8','Nguyễn Thị Hòa','female','1891-03-21','1971-04-14','p3','p5','b1','clan','Buôn bán'],
    ['p9','Phạm Thị Mai','female','1890-05-02','1970-01-08',null,null,'b2','spouse',''],
    ['p10','Nguyễn Văn Minh','male','1912-07-18','1988-02-02','p6','p9','b2','lineage','Giáo viên'],
    ['p11','Nguyễn Thị Thu','female','1915-11-13','1997-08-20','p6','p9','b2','clan','Y tá'],
    ['p12','Nguyễn Văn Nam','male','1919-04-04','1993-10-30','p6','p9','b3','lineage','Kỹ sư'],
    ['p13','Nguyễn Văn Quang','male','1942-02-11','2010-05-19','p10',null,'b2','lineage','Kiến trúc sư'],
    ['p14','Nguyễn Thị Ánh','female','1945-08-09','', 'p10',null,'b2','clan','Giáo viên'],
    ['p15','Nguyễn Văn Hải','male','1948-09-22','', 'p12',null,'b3','lineage','Bác sĩ'],
    ['p16','Nguyễn Thị Lan','female','1951-12-02','', 'p12',null,'b3','clan','Dược sĩ'],
    ['p17','Nguyễn Văn Hùng','male','1968-05-30','', 'p13',null,'b2','lineage','Doanh nhân'],
    ['p18','Nguyễn Thị Hà','female','1970-10-16','', 'p13',null,'b2','clan','Kế toán'],
    ['p19','Nguyễn Văn Tâm','male','1975-01-25','', 'p15',null,'b3','lineage','Kỹ sư phần mềm'],
    ['p20','Nguyễn Thị Nga','female','1978-04-03','', 'p15',null,'b3','clan','Nhà báo'],
    ['p21','Nguyễn Minh Khang','male','1991-06-12','', 'p17',null,'b2','lineage','Kiến trúc sư'],
    ['p22','Nguyễn Minh Châu','female','1994-03-07','', 'p17',null,'b2','clan','Bác sĩ'],
    ['p23','Nguyễn Hoàng Long','male','1998-11-21','', 'p19',null,'b3','lineage','Sinh viên'],
    ['p24','Nguyễn Hoài An','female','2001-07-01','', 'p19',null,'b3','clan','Nhà thiết kế'],
    ['p25','Nguyễn Gia Bảo','male','2018-09-13','', 'p21',null,'b2','lineage',''],
    ['p26','Nguyễn Gia Hân','female','2021-01-06','', 'p21',null,'b2','clan',''],
    ['p27','Trần Gia Linh','female','1996-02-17','', 'p14',null,'b2','external',''],
    ['p28','Trần Minh Anh','male','2019-08-19','', 'p27',null,'b2','external',''],
    ['p29','Nguyễn Văn Lộc','male','1916-03-03','1979-04-04','p7',null,'b1','lineage','Thợ mộc'],
    ['p30','Nguyễn Văn Sơn','male','1940-05-08','2001-10-10','p29',null,'b1','lineage','Bộ đội'],
    ['p31','Nguyễn Văn Bình','male','1964-12-12','', 'p30',null,'b1','lineage','Công chức'],
    ['p32','Nguyễn Thị Bình','female','1966-02-14','', 'p30',null,'b1','clan','Giáo viên'],
    ['p33','Nguyễn Quốc Việt','male','1987-09-09','', 'p31',null,'b1','lineage','Kỹ sư'],
    ['p34','Nguyễn Thị Yến','female','1990-07-07','', 'p31',null,'b1','clan','Điều dưỡng'],
    ['p35','Nguyễn Nhật Minh','male','2012-04-18','', 'p33',null,'b1','lineage','Học sinh'],
    ['p36','Nguyễn Nhật Hạ','female','2015-06-20','', 'p33',null,'b1','clan','Học sinh']
  ];
  const persons=raw.map((r,i)=>({id:r[0],code:'NV-'+String(i+1).padStart(4,'0'),name:r[1],gender:r[2],birth:r[3],death:r[4],fatherId:r[5],motherId:r[6],branchId:r[7],membership:r[8],occupation:r[9],hometown:branches.find(b=>b.id===r[7])?.place||'',bio:i===0?'Thủy tổ đời thứ nhất, người khai lập dòng họ tại địa phương.':'',avatar:'',createdAt:new Date(Date.now()-i*86400000).toISOString()}));
  return {version:1,clan:{name:'Dòng họ Nguyễn Văn',origin:'Nam Định',founderId:'p1',history:'Dòng họ Nguyễn Văn hình thành từ thế kỷ XIX, coi trọng hiếu học, nghĩa tình và gìn giữ nề nếp gia phong.',compiler:'Ban biên soạn Gia phả',lineageMode:'patrilineal'},branches,persons,families:[{id:'f1',husbandId:'p1',wifeId:'p2'},{id:'f2',husbandId:'p3',wifeId:'p5'},{id:'f3',husbandId:'p6',wifeId:'p9'}],media:[{id:'m1',title:'Từ đường dòng họ',category:'Nhà thờ họ',data:''},{id:'m2',title:'Gia phả cổ',category:'Tài liệu lịch sử',data:''}],events:[],updatedAt:new Date().toISOString()};
}
let legacyDb;try{legacyDb=JSON.parse(localStorage.getItem(STORE))||emptyDb()}catch{legacyDb=emptyDb()}
let workspaces;try{workspaces=JSON.parse(localStorage.getItem(WORKSPACES_STORE))||[]}catch{workspaces=[]}
if(!workspaces.length){workspaces=[{id:'clan-default',name:legacyDb.clan.name||'Gia phả dòng họ'}];localStorage.setItem(WORKSPACES_STORE,JSON.stringify(workspaces));localStorage.setItem(`${STORE}.clan-default`,JSON.stringify(legacyDb))}
let activeWorkspaceId=localStorage.getItem(ACTIVE_WORKSPACE_STORE)||workspaces[0].id;
if(!workspaces.some(w=>w.id===activeWorkspaceId))activeWorkspaceId=workspaces[0].id;
let db;try{db=JSON.parse(localStorage.getItem(`${STORE}.${activeWorkspaceId}`))||emptyDb()}catch{db=emptyDb()}
let currentView='dashboard',avatarData='';
const save=()=>{try{db.updatedAt=new Date().toISOString();localStorage.setItem(`${STORE}.${activeWorkspaceId}`,JSON.stringify(db));const item=workspaces.find(w=>w.id===activeWorkspaceId);if(item)item.name=db.clan.name||'Gia phả chưa đặt tên';localStorage.setItem(WORKSPACES_STORE,JSON.stringify(workspaces));localStorage.setItem(ACTIVE_WORKSPACE_STORE,activeWorkspaceId);return true}catch(error){console.error('Không thể lưu dữ liệu',error);toast('Không thể lưu: bộ nhớ trình duyệt có thể đã đầy. Hãy sao lưu dữ liệu và giảm ảnh dung lượng lớn.');return false}};
const person=id=>db.persons.find(p=>p.id===id);
const branch=id=>db.branches.find(b=>b.id===id);
const wivesOf=fatherId=>db.persons.filter(x=>x.gender==='female'&&x.membership==='spouse'&&x.spouseOfId===fatherId);
const hasMultipleWives=fatherId=>wivesOf(fatherId).length>=2;
function roomLabel(m){if(!m)return'Chưa xác định Phòng';const titles={'1':'bà Cả','2':'bà Hai','3':'bà Ba','4':'bà Tư','5':'bà Năm'};return `Phòng ${titles[m.marriageOrder]||'người mẹ'} – ${m.name}`}
function generation(id,seen=new Set()){if(!id||seen.has(id))return null;seen.add(id);const p=person(id);if(!p)return null;if(p.generationOverride&&Number(p.generationOverride)>0)return Number(p.generationOverride);if(p.id===db.clan.founderId)return 1;const parent=p.fatherId?person(p.fatherId):null;if(!parent||parent.gender!=='male'||parent.membership==='external')return null;const g=generation(parent.id,seen);return g?g+1:null}
function isMain(p){return p.membership==='lineage'||p.membership==='clan'}
function personDisplayCompare(a,b){const ga=generation(a.id)||999,gb=generation(b.id)||999,ba=branch(a.branchId),bb=branch(b.branchId),oa=Number(ba?.order)||Number(String(ba?.code||'').match(/\d+/)?.[0])||Number(a.branchOrder)||999,ob=Number(bb?.order)||Number(String(bb?.code||'').match(/\d+/)?.[0])||Number(b.branchOrder)||999;return ga-gb||oa-ob||a.name.localeCompare(b.name,'vi')||String(a.code||'').localeCompare(String(b.code||''),'vi')}
function normalizeSearch(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[đĐ]/g,'d').toLowerCase().replace(/[^a-z0-9]+/g,'')}
function duplicateSignature(p){if(!p)return'';const b=branch(p.branchId),parent=branch(b?.parentBranchId),branchPosition=b?[Number(b.order)||'',Number(b.startGeneration)||'',Number(parent?.order)||'',normalizeSearch(parent?.code||parent?.name||b.code||b.name)].join(':'):'none';return [normalizeSearch(p.name),generation(p.id)||'',p.gender||'',p.membership||'',branchPosition,p.fatherId||'',p.motherId||'',normalizeSearch(p.birth),normalizeSearch(p.death)].join('|')}
function childrenOf(id,includeExternal=false){return db.persons.filter(p=>p.fatherId===id||p.motherId===id).filter(p=>includeExternal||p.membership!=='external').sort(personDisplayCompare)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function avatar(p,cls='avatar'){return p?.avatar?`<img class="${cls}" src="${p.avatar}" alt="${esc(p.name)}">`:`<span class="${cls}">${initials(p?.name)}</span>`}

function renderDashboard(){
 const main=db.persons.filter(isMain),gens=main.map(p=>generation(p.id)).filter(Boolean),max=Math.max(0,...gens),male=main.filter(p=>p.gender==='male').length,related=db.persons.length-main.length;
 const counts=Array.from({length:max},(_,i)=>main.filter(p=>generation(p.id)===i+1).length);
 $('#dashboard').innerHTML=`<div class="hero"><div><h2>${esc(db.clan.name)}</h2><p>“Uống nước nhớ nguồn · Gìn giữ cội nguồn cho muôn đời sau”</p></div><div class="crest">家</div></div>
 <div class="stats"><div class="stat"><small>Tổng số hồ sơ</small><b>${db.persons.length}</b><em>${main.length} thuộc dòng họ (${male} nam · ${main.length-male} nữ) · ${related} phối ngẫu/ngoại hệ</em></div><div class="stat"><small>Số thế hệ</small><b>${max} đời</b><em>Từ ${year(person(db.clan.founderId)?.birth)} đến nay</em></div><div class="stat"><small>Chi · Nhánh</small><b>${db.branches.length}</b><em>${db.branches.map(b=>b.code).join(' · ')}</em></div><div class="stat"><small>Kho tư liệu</small><b>${db.media.length}</b><em>ảnh và tài liệu</em></div></div>
 <div class="grid-2"><div class="panel"><div class="panel-head"><h3>Cập nhật gần đây</h3><button class="btn" onclick="showView('members')">Xem tất cả</button></div><div class="activity">${db.persons.slice().sort((a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||''))).slice(0,5).map(p=>`<div class="activity-item">${avatar(p)}<div><b>${esc(p.name)}</b><small>${p.code} · ${branch(p.branchId)?.name||'Chưa xếp chi'}</small></div></div>`).join('')}</div></div>
 <div class="panel"><div class="panel-head"><h3>Thành viên theo đời</h3></div><div class="generation-bars">${counts.map((n,i)=>`<div><i style="height:${Math.max(8,n/Math.max(...counts)*110)}px"></i>Đời ${i+1}<br><b>${n}</b></div>`).join('')}</div></div></div>`;
}
function treeNode(p,depth=0){if(!p||depth>12)return'';const adoptedStop=p.childRelation==='adopted',stop=(db.clan.lineageMode==='patrilineal'&&p.gender==='female')||adoptedStop;const kids=stop?[]:childrenOf(p.id).filter(isMain);const relation=p.childRelation==='adopted_heir'?'<small>Con nuôi kế tự · Được nối dõi</small>':adoptedStop?'<small class="stop">Con nuôi · Không nối dõi</small>':'';return `<li class="${kids.length?'':'leaf'}"><div class="person-card ${p.gender==='female'?'female':''}" onclick="showPerson('${p.id}')">${avatar(p)}<b>${esc(p.name)}</b><small>Đời ${generation(p.id)||'—'}</small>${relation}${!adoptedStop&&stop?'<small class="stop">Xuất giá · Dừng nhánh</small>':''}</div>${kids.length?`<ul>${kids.map(k=>treeNode(k,depth+1)).join('')}</ul>`:''}</li>`}
function renderTree(){const root=person(db.clan.founderId)||db.persons.find(isMain);treeZoomLevel=1;$('#tree').innerHTML=`<div class="toolbar"><select id="treeBranch"><option value="">Toàn dòng họ</option>${db.branches.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}</select><button class="btn" onclick="window.print()">⤓ In / PDF</button><button class="btn" onclick="startAreaExport()">▦ Chọn vùng & Xuất</button><div class="zoom-controls"><button class="btn small" onclick="treeZoom(-0.1)" title="Thu nhỏ">－</button><span id="zoomLabel">100%</span><button class="btn small" onclick="treeZoom(0.1)" title="Phóng to">＋</button><button class="btn small" onclick="treeZoomReset()" title="Về 100%">Đặt lại</button></div><span class="chip">Nam hệ: Nữ dừng nhánh</span><span class="chip hint">Kéo chuột để di chuyển xem</span></div><div class="tree-wrap">${root?`<div class="tree-zoom-viewport"><ul class="tree-root">${treeNode(root)}</ul></div>`:`<div class="empty"><h3>Gia phả đang trống</h3><p>Hãy thêm Thủy tổ hoặc thành viên đầu tiên để bắt đầu xây dựng cây.</p><button class="btn primary" onclick="openPersonForm()">＋ Thêm thành viên đầu tiên</button></div>`}</div>`;$('#treeBranch').onchange=e=>{const b=branch(e.target.value);const r=b&&person(b.founderId);const tree=$('.tree-root');if(tree)tree.innerHTML=r?treeNode(r):treeNode(root);treeZoomLevel=1;applyTreeZoom()};ensureTreePanHandlers();applyTreeZoom()}
function renderMembers(q=''){const x=q.toLowerCase();const rows=db.persons.filter(p=>!x||[p.name,p.code,p.hometown,p.occupation,branch(p.branchId)?.name].join(' ').toLowerCase().includes(x));$('#members').innerHTML=`<div class="toolbar"><input class="grow" id="memberSearch" placeholder="Tìm trong danh sách..." value="${esc(q)}"><select id="memberBranch"><option value="">Tất cả chi nhánh</option>${db.branches.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}</select><button class="btn primary" onclick="openPersonForm()">＋ Thêm người</button></div><div class="table-wrap"><table><thead><tr><th>Thành viên</th><th>Đời</th><th>Chi · Nhánh</th><th>Năm sinh</th><th>Vai trò</th><th></th></tr></thead><tbody>${rows.map(p=>`<tr data-branch="${p.branchId}"><td><div class="name-cell">${avatar(p)}<div><b>${esc(p.name)}</b><small>${p.code}</small></div></div></td><td>${generation(p.id)||'—'}</td><td>${esc(branch(p.branchId)?.name||'—')}</td><td>${year(p.birth)}</td><td><span class="chip ${p.gender}">${p.membership==='external'?'Ngoại hệ':p.membership==='spouse'?'Phối ngẫu':p.gender==='female'?'Nữ thành viên dòng họ':'Thành viên Nam hệ'}</span></td><td class="actions"><button onclick="showPerson('${p.id}')">◎</button><button onclick="openPersonForm('${p.id}')">✎</button></td></tr>`).join('')}</tbody></table></div>`;$('#memberSearch').oninput=e=>renderMembers(e.target.value);$('#memberBranch').onchange=e=>$$('tbody tr').forEach(r=>r.hidden=!!e.target.value&&r.dataset.branch!==e.target.value)}
const renderMembersInSavedOrder=renderMembers;renderMembers=function(q=''){renderMembersInSavedOrder('');const tbody=$('#members tbody'),search=$('#memberSearch'),branchSelect=$('#memberBranch');if(!tbody)return;search.placeholder='Chỉ tìm trong Họ và tên thành viên...';search.value=q;const rows=[...tbody.rows].sort((a,b)=>{const codeA=a.querySelector('.name-cell small')?.textContent||'',codeB=b.querySelector('.name-cell small')?.textContent||'',pa=db.persons.find(p=>p.code===codeA),pb=db.persons.find(p=>p.code===codeB);return pa&&pb?personDisplayCompare(pa,pb):0}),apply=()=>{const keyword=normalizeSearch(search.value),branchId=branchSelect.value,matched=rows.filter(row=>{const code=row.querySelector('.name-cell small')?.textContent||'',p=db.persons.find(x=>x.code===code),memberName=normalizeSearch(p?.name);return (!keyword||memberName.includes(keyword))&&(!branchId||p?.branchId===branchId)});tbody.replaceChildren(...matched)};search.oninput=apply;branchSelect.onchange=apply;apply()};
const renderMembersWithDuplicateMerge=renderMembers;renderMembers=function(q=''){renderMembersWithDuplicateMerge(q);const tbody=$('#members tbody');if(!tbody)return;[...tbody.rows].forEach(row=>{const code=row.querySelector('.name-cell small')?.textContent||'',p=db.persons.find(x=>x.code===code),duplicates=p?db.persons.filter(x=>x.id!==p.id&&duplicateSignature(x)===duplicateSignature(p)):[];if(!duplicates.length)return;const actions=row.querySelector('.actions');if(actions&&!actions.querySelector('.merge-duplicate'))actions.insertAdjacentHTML('afterbegin',`<button class="merge-duplicate" title="Hợp nhất hồ sơ trùng" onclick="mergeVerifiedDuplicate('${p.id}')">⇄ Hợp nhất</button>`)})};
const renderMembersWithSafeCancel=renderMembers;renderMembers=function(q=''){renderMembersWithSafeCancel(q);const tbody=$('#members tbody');if(!tbody)return;[...tbody.rows].forEach(row=>{const code=row.querySelector('.name-cell small')?.textContent||'',p=db.persons.find(x=>x.code===code),actions=row.querySelector('.actions');if(p&&actions&&!actions.querySelector('.cancel-extra-profile'))actions.insertAdjacentHTML('beforeend',`<button class="cancel-extra-profile" title="Hủy hồ sơ nhập thừa" onclick="cancelExtraProfile('${p.id}')">🗑 Hủy</button>`)})};
window.cancelExtraProfile=function(id){const p=person(id);if(!p)return;const children=db.persons.filter(x=>x.fatherId===id||x.motherId===id),spouseLinks=db.persons.filter(x=>x.spouseOfId===id),foundedBranches=db.branches.filter(b=>b.founderId===id),familyLinks=(db.families||[]).filter(f=>f.husbandId===id||f.wifeId===id),isFounder=db.clan.founderId===id;if(children.length||spouseLinks.length||foundedBranches.length||familyLinks.length||isFounder){alert(`Không thể hủy ${p.name} (${p.code}) vì hồ sơ đang có liên kết:\n\n• ${children.length} người con\n• ${spouseLinks.length+familyLinks.length} quan hệ phối ngẫu/gia đình\n• ${foundedBranches.length} Chi–Nhánh\n${isFounder?'• Đây là hồ sơ Thủy tổ\n':''}\nHãy dùng Hợp nhất hoặc chuyển các liên kết sang đúng hồ sơ trước.`);return}if(!confirm(`Hủy hồ sơ nhập thừa ${p.name} (${p.code})?\n\nHồ sơ sẽ được đưa vào thùng tạm và có thể khôi phục.`))return;const before=JSON.stringify(db);db.deletedPersons??=[];db.deletedPersons.push({...p,deletedAt:new Date().toISOString()});db.persons=db.persons.filter(x=>x.id!==id);if(!save()){db=JSON.parse(before);return}renderAll();toast('Đã đưa hồ sơ vào thùng tạm')};
window.mergeDuplicate=function(sourceId){const source=person(sourceId);if(!source)return;const candidates=db.persons.filter(p=>p.id!==source.id&&normalizeSearch(p.name)===normalizeSearch(source.name));if(!candidates.length)return toast('Không tìm thấy hồ sơ trùng tên để hợp nhất');const list=candidates.map(p=>`${p.code} — ${p.name} — Đời ${generation(p.id)||'chưa rõ'}`).join('\n'),targetCode=prompt(`Nhập MÃ HỒ SƠ cần GIỮ LẠI:\n\n${list}`,candidates[0].code);if(!targetCode)return;const target=db.persons.find(p=>p.id!==source.id&&String(p.code).toLowerCase()===targetCode.trim().toLowerCase());if(!target)return toast('Không tìm thấy mã hồ sơ cần giữ');if(!confirm(`Hợp nhất ${source.code} vào ${target.code}?\n\nMọi con cháu, phối ngẫu và Chi–Nhánh sẽ được chuyển sang ${target.code}.`))return;const before=JSON.stringify(db),empty=v=>v==null||v==='';Object.entries(source).forEach(([key,value])=>{if(!['id','code','createdAt','updatedAt','bio'].includes(key)&&empty(target[key])&&!empty(value))target[key]=value});if(source.bio&&source.bio!==target.bio)target.bio=[target.bio,source.bio].filter(Boolean).join('\n');const sourceBranches=db.branches.filter(b=>b.founderId===source.id),targetBranch=db.branches.find(b=>b.founderId===target.id);sourceBranches.forEach(sb=>{if(targetBranch&&targetBranch.id!==sb.id){db.persons.forEach(p=>{if(p.branchId===sb.id)p.branchId=targetBranch.id});db.branches.forEach(b=>{if(b.parentBranchId===sb.id)b.parentBranchId=targetBranch.id});db.branches=db.branches.filter(b=>b.id!==sb.id)}else sb.founderId=target.id});db.persons.forEach(p=>{['fatherId','motherId','spouseOfId','roomMotherId'].forEach(key=>{if(p[key]===source.id)p[key]=target.id});if(p.id===target.id){if(p.fatherId===target.id)p.fatherId='';if(p.motherId===target.id)p.motherId=''}});db.families?.forEach(f=>{['husbandId','wifeId'].forEach(key=>{if(f[key]===source.id)f[key]=target.id})});if(db.clan.founderId===source.id)db.clan.founderId=target.id;target.updatedAt=new Date().toISOString();db.persons=db.persons.filter(p=>p.id!==source.id);synchronizeLinkedData();cleanupLegacyRootBranches();if(!save()){db=JSON.parse(before);return}renderAll();toast(`Đã hợp nhất vào ${target.code}; các quan hệ được giữ nguyên`)};
window.mergeVerifiedDuplicate=function(sourceId){const source=person(sourceId),candidates=db.persons.filter(p=>p.id!==sourceId&&duplicateSignature(p)===duplicateSignature(source));if(!candidates.length)return toast('Hai hồ sơ không trùng đủ Đời, Nhánh và quan hệ');const list=candidates.map(p=>`${p.code} — ${p.name} — Đời ${generation(p.id)||'chưa rõ'}`).join('\n'),chosen=prompt(`Nhập MÃ HỒ SƠ cần GIỮ LẠI:\n\n${list}`,candidates[0].code);if(!chosen)return;if(!candidates.some(p=>p.code.toLowerCase()===chosen.trim().toLowerCase()))return toast('Chỉ được chọn hồ sơ trùng đầy đủ thông tin');const nativePrompt=window.prompt;window.prompt=()=>chosen;try{mergeDuplicate(sourceId)}finally{window.prompt=nativePrompt}};
function renderBranches(){$('#branches').innerHTML=`<div class="toolbar"><div class="grow"></div><button class="btn primary" onclick="addBranch()">＋ Thêm chi nhánh</button></div><div class="branch-grid">${db.branches.slice().sort((a,b)=>(Number(a.startGeneration)||999)-(Number(b.startGeneration)||999)||(Number(a.order)||Number(String(a.code||'').match(/\d+/)?.[0])||999)-(Number(b.order)||Number(String(b.code||'').match(/\d+/)?.[0])||999)||a.name.localeCompare(b.name,'vi')).map(b=>`<div class="panel branch-card"><small>${b.code}</small><br><b>${esc(b.name)}</b><p>${esc(b.description)}</p><span class="chip">${db.persons.filter(p=>p.branchId===b.id&&isMain(p)).length} thành viên</span> <span class="chip">${esc(b.place)}</span></div>`).join('')}</div>`}
function renderMedia(){$('#media').innerHTML=`<div class="toolbar"><div class="grow"></div><label class="btn primary">＋ Thêm tư liệu<input id="mediaInput" type="file" accept="image/*,.pdf" hidden></label></div><div class="media-grid">${db.media.map(m=>`<div class="media-card" ${m.data?`style="background-image:url('${m.data}')"`:''}><span><b>${esc(m.title)}</b><br><small>${esc(m.category)}</small></span></div>`).join('')}</div>`;$('#mediaInput').onchange=addMedia}
function renderBook(){const main=db.persons.filter(isMain).sort((a,b)=>(generation(a.id)||99)-(generation(b.id)||99));$('#book').innerHTML=`<div class="toolbar no-print"><button class="btn primary" onclick="window.print()">⤓ Xuất PDF / In sách</button><span class="chip">Khổ A4 · Mẫu truyền thống</span></div><div class="book-cover"><div class="seal">家</div><h2>GIA PHẢ</h2><h3>${esc(db.clan.name.toUpperCase())}</h3><p>${esc(db.clan.origin)} · Biên soạn năm ${new Date().getFullYear()}<br><br>${esc(db.clan.compiler)}</p></div><div class="print-section panel"><h2>Lịch sử dòng họ</h2><p>${esc(db.clan.history)}</p><h2>Danh sách các đời</h2>${Array.from(new Set(main.map(p=>generation(p.id)).filter(Boolean))).map(g=>`<h3>Đời thứ ${g}</h3><ol>${main.filter(p=>generation(p.id)===g).map(p=>`<li><b>${esc(p.name)}</b> (${year(p.birth)}${p.death?'–'+year(p.death):''}) · ${esc(branch(p.branchId)?.name||'')}</li>`).join('')}</ol>`).join('')}</div>`}
function renderData(){$('#data').innerHTML=`<div class="panel"><div class="panel-head"><h3>Dữ liệu thuộc quyền của gia đình</h3><span class="chip">Cập nhật ${new Date(db.updatedAt).toLocaleString('vi-VN')}</span></div><p>Mọi chức năng cốt lõi chạy trên thiết bị này. Hãy sao lưu định kỳ và giữ tệp ở ít nhất hai nơi an toàn.</p></div><div class="export-grid" style="margin-top:16px"><div class="panel data-card" onclick="exportJSON()">◈<strong>Sao lưu toàn bộ</strong><p>Xuất JSON chứa dữ liệu, ảnh và cấu hình. Có thể khôi phục đầy đủ.</p></div><div class="panel data-card" onclick="pickImport()">↥<strong>Khôi phục / Nhập</strong><p>Nhận JSON backup, GEDCOM hoặc CSV. Dữ liệu được kiểm tra trước khi nhập.</p></div><div class="panel data-card" onclick="exportGEDCOM()">⌁<strong>Xuất GEDCOM 7</strong><p>Định dạng trao đổi gia phả, giữ cá nhân và quan hệ cha mẹ.</p></div><div class="panel data-card" onclick="exportCSV()">▦<strong>Xuất CSV</strong><p>Danh sách thành viên tiếng Việt, mở được trong Excel.</p></div><div class="panel data-card" onclick="showView('book')">▤<strong>Xuất sách PDF</strong><p>Bìa, lịch sử và danh sách thành viên theo đời.</p></div><div class="panel data-card" onclick="resetDemo()">↻<strong>Khôi phục dữ liệu mẫu</strong><p>Tạo lại 6 đời, 36 hồ sơ và 3 chi nhánh để trải nghiệm.</p></div></div>`}
const renderDataWithDeletedProfiles=renderData;renderData=function(){renderDataWithDeletedProfiles();if(!(db.deletedPersons||[]).length)return;const panel=$('#data .panel'),last=db.deletedPersons[db.deletedPersons.length-1];panel?.insertAdjacentHTML('beforeend',`<p><button class="btn" onclick="restoreLastDeletedProfile()">↶ Khôi phục hồ sơ vừa hủy</button> <span class="chip">${db.deletedPersons.length} hồ sơ trong thùng tạm · gần nhất: ${esc(last.name)} (${esc(last.code)})</span></p>`)};
window.restoreLastDeletedProfile=function(){const removed=db.deletedPersons?.pop();if(!removed)return;const {deletedAt,...profile}=removed;if(db.persons.some(p=>p.id===profile.id))profile.id=uid();if(db.persons.some(p=>p.code===profile.code))profile.code='NV-'+String(db.persons.length+1).padStart(4,'0');db.persons.push(profile);save();renderAll();showView('data');toast('Đã khôi phục hồ sơ vừa hủy')};
function renderSettings(){$('#settings').innerHTML=`<div class="panel settings-form"><h3>Thông tin dòng họ</h3><br><label>Tên dòng họ<input id="clanName" value="${esc(db.clan.name)}"></label><label>Nguyên quán<input id="clanOrigin" value="${esc(db.clan.origin)}"></label><label>Lịch sử<textarea id="clanHistory" rows="5">${esc(db.clan.history)}</textarea></label><label>Người / Ban biên soạn<input id="clanCompiler" value="${esc(db.clan.compiler)}"></label><label>Quy ước gia phả<select id="lineageMode"><option value="patrilineal" ${db.clan.lineageMode==='patrilineal'?'selected':''}>Nam hệ truyền thống</option><option value="extended" ${db.clan.lineageMode==='extended'?'selected':''}>Mở rộng hai bên</option></select></label><div class="rule-hint">Chuyển chế độ chỉ thay đổi cách hiển thị. Không xóa bất kỳ hồ sơ hoặc quan hệ đã lưu nào.</div><br><button class="btn primary" id="saveSettings">Lưu cài đặt</button></div>`;$('#saveSettings').onclick=()=>{db.clan.name=$('#clanName').value;db.clan.origin=$('#clanOrigin').value;db.clan.history=$('#clanHistory').value;db.clan.compiler=$('#clanCompiler').value;db.clan.lineageMode=$('#lineageMode').value;save();renderAll();toast('Đã lưu cài đặt')}}
const titles={dashboard:['Tổng quan','Bức tranh chung về dòng họ'],tree:['Cây gia phả','Sơ đồ nhiều thế hệ theo quy ước Nam hệ'],members:['Thành viên','Tra cứu và quản lý hồ sơ'],branches:['Chi · Nhánh','Cấu trúc các nhánh trong dòng họ'],media:['Kho tư liệu','Ảnh, giấy tờ và tư liệu lịch sử'],book:['Sách gia phả','Bản in được sinh từ dữ liệu gốc'],data:['Dữ liệu & sao lưu','Nhập, xuất và bảo vệ dữ liệu'],settings:['Cài đặt','Thông tin và quy ước dòng họ']};
window.showView=function(v){currentView=v;$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#pageTitle').textContent=titles[v][0];$('#pageSub').textContent=titles[v][1];$('.sidebar').classList.remove('open');window.scrollTo(0,0)};
function renderWorkspaceSwitcher(){const select=$('#clanSwitcher');if(!select)return;select.innerHTML=workspaces.map(w=>`<option value="${w.id}" ${w.id===activeWorkspaceId?'selected':''}>${esc(w.name)}</option>`).join('')}
function switchWorkspace(id){if(id===activeWorkspaceId)return;save();activeWorkspaceId=id;localStorage.setItem(ACTIVE_WORKSPACE_STORE,id);try{db=JSON.parse(localStorage.getItem(`${STORE}.${id}`))||emptyDb()}catch{db=emptyDb()}currentView='dashboard';renderAll();toast(`Đã mở ${db.clan.name}`)}
function createWorkspace(){$('#clanForm').reset();$('#clanDialog').showModal()}
function renderAll(){const brandName=$('.brand small');if(brandName)brandName.textContent=db.clan.name;renderWorkspaceSwitcher();renderDashboard();renderTree();renderMembers();renderBranches();renderMedia();renderBook();renderData();renderSettings();showView(currentView)}

window.openPersonForm=function(id=''){const p=person(id)||{};avatarData=p.avatar||'';const f=$('#personForm');f.reset();f.elements.id.value=p.id||'';f.elements.name.value=p.name||'';f.elements.gender.value=p.gender||'male';f.elements.membership.value=p.membership||(p.gender==='female'?'clan':'lineage');f.elements.birth.value=p.birth||'';f.elements.death.value=p.death||'';f.elements.occupation.value=p.occupation||'';f.elements.hometown.value=p.hometown||'';f.elements.bio.value=p.bio||'';f.elements.fatherId.innerHTML='<option value="">— Chưa rõ —</option>'+db.persons.filter(x=>x.gender==='male'&&x.id!==id).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');f.elements.motherId.innerHTML='<option value="">— Chưa rõ —</option>'+db.persons.filter(x=>x.gender==='female'&&x.id!==id).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');f.elements.spouseOfId.innerHTML='<option value="">— Chọn người vợ/chồng —</option>'+db.persons.filter(x=>x.id!==id&&x.membership!=='spouse').map(x=>`<option value="${x.id}">${esc(x.name)} (${x.code})</option>`).join('');f.elements.branchId.innerHTML='<option value="">— Chưa xếp —</option>'+db.branches.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');f.elements.fatherId.value=p.fatherId||'';f.elements.motherId.value=p.motherId||'';f.elements.spouseOfId.value=p.spouseOfId||'';f.elements.marriageOrder.value=p.marriageOrder||'';f.elements.marriageDate.value=p.marriageDate||'';f.elements.marriageStatus.value=p.marriageStatus||'married';f.elements.branchId.value=p.branchId||'';$('#formTitle').textContent=id?'Sửa hồ sơ':'Thêm thành viên';$('#avatarPreview').src=avatarData||'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="80" height="80"><rect width="100%" height="100%" fill="#e9dfd0"/><text x="50%" y="56%" text-anchor="middle" font-size="24" fill="#7b2f22">${initials(p.name)}</text></svg>`);toggleFemaleHint();toggleMarriageFields();$('#personDialog').showModal()}
const openPersonFormWithMarriage=window.openPersonForm;window.openPersonForm=function(id=''){openPersonFormWithMarriage(id);const p=person(id)||{},f=$('#personForm');f.elements.generationOverride.value=p.generationOverride||'';f.elements.birthCalendar.value=p.birthCalendar||'solar';f.elements.birthPrecision.value=p.birthPrecision||(p.birth?'exact':'unknown');f.elements.deathCalendar.value=p.deathCalendar||'lunar';f.elements.deathPrecision.value=p.deathPrecision||'daymonth';f.elements.deathLeapMonth.value=p.deathLeapMonth||'no';f.elements.anniversary.value=p.anniversary||'';f.elements.anniversaryCalendar.value=p.anniversaryCalendar||'lunar'}
const openPersonFormWithBranch=window.openPersonForm;window.openPersonForm=function(id=''){openPersonFormWithBranch(id);const p=person(id)||{},f=$('#personForm'),select=f.elements.branchId;select.innerHTML='<option value="">— Chưa xếp chi nhánh —</option>'+db.branches.map(x=>`<option value="${x.id}">${esc(x.name)} (${esc(x.code)})</option>`).join('')+'<option value="__new__">＋ Tạo chi nhánh mới…</option>';select.value=p.branchId||'';select.onchange=()=>{if(select.value!=='__new__')return;const name=prompt('Tên Chi / Nhánh mới:');if(!name){select.value='';return}const b={id:uid(),name:name.trim(),code:'C'+String(db.branches.length+1).padStart(2,'0'),place:'',description:'Chi nhánh mới'};db.branches.push(b);save();const option=document.createElement('option');option.value=b.id;option.textContent=`${b.name} (${b.code})`;select.insertBefore(option,select.lastElementChild);select.value=b.id;toast('Đã tạo và chọn chi nhánh mới')};f.elements.fatherId.onchange=()=>{const father=person(f.elements.fatherId.value);if(father?.branchId&&!select.value)select.value=father.branchId}}
const openPersonFormWithBranchOrigin=window.openPersonForm;window.openPersonForm=function(id=''){openPersonFormWithBranchOrigin(id);const p=person(id)||{},f=$('#personForm'),b=db.branches.find(x=>x.founderId===id);f.elements.startsBranch.value=b?'yes':(p.startsBranch||'no');f.elements.branchOrder.value=b?.order||p.branchOrder||'';f.elements.descendantBranchCount.value=p.descendantBranchCount??'';f.elements.declaredWifeCount.value=p.declaredWifeCount??'';$('.wife-count-field').hidden=!(f.elements.gender.value==='male'&&f.elements.membership.value==='lineage')}
const openPersonFormWithRoom=window.openPersonForm;window.openPersonForm=function(id=''){openPersonFormWithRoom(id);const p=person(id)||{},f=$('#personForm'),room=f.elements.roomMotherId,roomField=room.closest('label');const refresh=()=>{const fatherId=f.elements.fatherId.value,wives=wivesOf(fatherId),show=wives.length>=2;roomField.hidden=!show;room.innerHTML='<option value="">— Chưa xác định Phòng —</option>'+wives.map(x=>`<option value="${x.id}">${esc(roomLabel(x))}</option>`).join('');room.value=show&&wives.some(x=>x.id===(p.roomMotherId||p.motherId))?(p.roomMotherId||p.motherId):''};refresh();const oldFatherChange=f.elements.fatherId.onchange;f.elements.fatherId.onchange=()=>{oldFatherChange?.();refresh()};f.elements.motherId.onchange=()=>{const m=person(f.elements.motherId.value);room.value=hasMultipleWives(f.elements.fatherId.value)&&m?.membership==='spouse'?m.id:''};room.onchange=()=>{if(room.value)f.elements.motherId.value=room.value}}
function toggleFemaleHint(){const f=$('#personForm');$('#femaleHint').hidden=f.elements.gender.value!=='female';if(f.elements.gender.value==='female'&&f.elements.membership.value==='lineage')f.elements.membership.value='clan';$('.wife-count-field').hidden=!(f.elements.gender.value==='male'&&f.elements.membership.value==='lineage')}
function toggleMarriageFields(){const f=$('#personForm'),show=f.elements.membership.value==='spouse'||!!f.elements.spouseOfId.value;$$('.marriage-field').forEach(x=>x.hidden=!show);$$('.parent-field').forEach(x=>x.hidden=show);if(show){f.elements.fatherId.value='';f.elements.motherId.value=''}}
function updateLineageFields(){const f=$('#personForm'),id=f.elements.id.value,isSpouse=f.elements.membership.value==='spouse',isMaleLineage=f.elements.gender.value==='male'&&f.elements.membership.value==='lineage',fatherId=f.elements.fatherId.value,motherId=f.elements.motherId.value,father=person(fatherId),hasParents=!!(fatherId||motherId),generationValue=Number(f.elements.generationOverride.value)||(id?generation(id):(fatherId?(generation(fatherId)||0)+1:null)),isGenerationOne=isMaleLineage&&(generationValue===1||(!hasParents&&!id));const actualBrotherCount=fatherId?db.persons.filter(x=>x.id!==id&&x.gender==='male'&&x.membership==='lineage'&&x.fatherId===fatherId).length+1:0,declaredBranchCount=Number(father?.descendantBranchCount)||0,hasMultipleBranches=isMaleLineage&&!isGenerationOne&&!!fatherId&&(declaredBranchCount>=2||actualBrotherCount>=2),hideBranchPosition=!hasMultipleBranches;$$('.branch-assignment-field').forEach(x=>{const hide=isSpouse||hideBranchPosition;x.hidden=hide;x.style.display=hide?'none':''});$$('.branch-lineage-field').forEach(x=>{x.hidden=hideBranchPosition;x.style.display=hideBranchPosition?'none':''});$$('.descendant-count-field').forEach(x=>{x.hidden=!isMaleLineage;x.style.display=!isMaleLineage?'none':''});$('#branchOrderLabel').textContent=`Nhánh thứ mấy của đời thứ ${generationValue||'?'}?`;$('#singleChildHint').hidden=!(isMaleLineage&&!hasMultipleBranches);if(isSpouse||hideBranchPosition)f.elements.branchId.value='';if(hideBranchPosition){f.elements.startsBranch.value='no';f.elements.branchOrder.value=''}if(!isMaleLineage)f.elements.descendantBranchCount.value=''}
$('#personForm').elements.gender.onchange=()=>{toggleFemaleHint();updateLineageFields()};
$('#personForm').elements.membership.onchange=()=>{toggleFemaleHint();toggleMarriageFields();updateLineageFields()};
$('#personForm').elements.spouseOfId.onchange=toggleMarriageFields;
const openPersonFormWithLineageRules=window.openPersonForm;window.openPersonForm=function(id=''){openPersonFormWithLineageRules(id);const f=$('#personForm'),oldFather=f.elements.fatherId.onchange,oldMother=f.elements.motherId.onchange;f.elements.fatherId.onchange=()=>{oldFather?.();updateLineageFields()};f.elements.motherId.onchange=()=>{oldMother?.();updateLineageFields()};f.elements.generationOverride.onchange=updateLineageFields;updateLineageFields()}
const openPersonFormWithGenerationLabels=window.openPersonForm;window.openPersonForm=function(id=''){openPersonFormWithGenerationLabels(id);const f=$('#personForm');['fatherId','motherId','spouseOfId'].forEach(field=>{const select=f.elements[field],selected=select.value,options=[...select.options],fixed=options.filter(option=>!person(option.value)),people=options.filter(option=>person(option.value)).sort((a,b)=>personDisplayCompare(person(a.value),person(b.value)));people.forEach(option=>{const p=person(option.value);option.textContent=`${p.name} — Đời ${generation(p.id)||'chưa rõ'} (${p.code})`});select.replaceChildren(...fixed,...people);select.value=selected})}
const openPersonFormWithLocations=window.openPersonForm;window.openPersonForm=function(id=''){openPersonFormWithLocations(id);const p=person(id)||{},f=$('#personForm');f.elements.birthplace.value=p.birthplace||'';f.elements.residence.value=p.residence||'';const locations=[db.clan.origin,...db.branches.map(b=>b.place),...db.persons.flatMap(x=>[x.hometown,x.birthplace,x.residence])].map(x=>String(x||'').trim()).filter(Boolean),unique=[...new Set(locations)].sort((a,b)=>a.localeCompare(b,'vi'));$('#locationSuggestions').innerHTML=unique.map(x=>`<option value="${esc(x)}"></option>`).join('')}
function updateModernLocationFields(){const f=$('#personForm'),id=f.elements.id.value,g=Number(f.elements.generationOverride.value)||(id?generation(id):null),show=g>=10;$$('.modern-location-field').forEach(field=>{field.hidden=!show;field.style.display=show?'':'none'})}
const updateLineageFieldsBeforeModernLocations=updateLineageFields;updateLineageFields=function(){updateLineageFieldsBeforeModernLocations();updateModernLocationFields()};
const PERSON_DRAFT_PREFIX='giaPhaViet.personDraft';let personDraftDirty=false,personDraftTimer;const personDraftKey=id=>`${PERSON_DRAFT_PREFIX}.${activeWorkspaceId}.${id||'new'}`;
function writePersonDraft(force=false){const f=$('#personForm');if(!f.open&&!f.closest('dialog')?.open)return;if(!personDraftDirty&&!force)return;try{localStorage.setItem(personDraftKey(f.elements.id.value),JSON.stringify({savedAt:new Date().toISOString(),values:Object.fromEntries(new FormData(f)),avatar:avatarData}));personDraftDirty=false}catch(error){console.warn('Không thể tự lưu bản nháp',error)}}
$('#personForm').addEventListener('input',()=>{personDraftDirty=true;clearTimeout(personDraftTimer);personDraftTimer=setTimeout(()=>writePersonDraft(),1000)});$('#personForm').addEventListener('change',()=>{personDraftDirty=true;clearTimeout(personDraftTimer);personDraftTimer=setTimeout(()=>writePersonDraft(),1000)});setInterval(()=>writePersonDraft(),15000);
const openPersonFormWithDraftRecovery=window.openPersonForm;window.openPersonForm=function(id=''){openPersonFormWithDraftRecovery(id);const f=$('#personForm'),p=person(id);let draft;try{draft=JSON.parse(localStorage.getItem(personDraftKey(id))||'null')}catch{}if(draft&&draft.savedAt>String(p?.updatedAt||p?.createdAt||'')){Object.entries(draft.values||{}).forEach(([name,value])=>{const field=f.elements[name];if(field&&field.type!=='file')field.value=value});f.elements.fatherId.dispatchEvent(new Event('change'));Object.entries(draft.values||{}).forEach(([name,value])=>{const field=f.elements[name];if(field&&field.type!=='file')field.value=value});avatarData=draft.avatar||avatarData;if(avatarData)$('#avatarPreview').src=avatarData;toggleFemaleHint();toggleMarriageFields();updateLineageFields();toast('Đã phục hồi bản nháp tự động lưu')}personDraftDirty=false};
$('#personForm').addEventListener('submit',e=>{const key=personDraftKey(e.currentTarget.elements.id.value);setTimeout(()=>{if(!$('#personDialog').open){localStorage.removeItem(key);personDraftDirty=false}},0)});
function synchronizeLinkedData(){const ids=new Set(db.persons.map(p=>p.id));db.persons.forEach(p=>{if(p.fatherId&&!ids.has(p.fatherId))p.fatherId='';if(p.motherId&&!ids.has(p.motherId))p.motherId='';if(p.spouseOfId&&!ids.has(p.spouseOfId))p.spouseOfId='';if(p.membership==='spouse'){p.fatherId='';p.motherId='';p.roomMotherId='';p.branchId='';p.startsBranch='no';p.branchOrder=''}else if(hasMultipleWives(p.fatherId)){p.roomMotherId=p.motherId||''}else p.roomMotherId=''});db.branches.forEach(b=>{if(b.parentBranchId!==b.id)return;const founder=person(b.founderId),father=person(founder?.fatherId);b.parentBranchId=father?.branchId&&father.branchId!==b.id?father.branchId:''});db.branches.filter(b=>b.founderId&&(b.order||b.startGeneration)).sort((a,b)=>(Number(a.startGeneration)||0)-(Number(b.startGeneration)||0)).forEach(b=>{const founder=person(b.founderId);if(!founder)return;const parentBranch=b.parentBranchId!==b.id?branch(b.parentBranchId):null,parentName=parentBranch?.name||'Chi chưa xác định',order=Number(b.order)||Number(founder.branchOrder)||1,startGeneration=Number(founder.generationOverride)||generation(founder.id)||Number(b.startGeneration)||1,roomName=hasMultipleWives(founder.fatherId)?roomLabel(person(founder.motherId)):'',roomPart=roomName?` – ${roomName}`:'';Object.assign(b,{order,startGeneration,name:`Nhánh thứ ${order}${roomPart} – thuộc ${parentName} – khởi từ đời thứ ${startGeneration}`,description:`Nhánh thứ ${order}, ${roomName?roomName+', ':''}thuộc ${parentName}, do ${founder.name} khởi đầu ở đời thứ ${startGeneration}`})})}
function deduplicateSavedProfiles(){const latestPersons=new Map();db.persons.forEach(p=>latestPersons.set(p.id,p));db.persons=[...latestPersons.values()];const latestBranchByFounder=new Map();db.branches.forEach(b=>{if(b.founderId&&(b.order||b.startGeneration))latestBranchByFounder.set(b.founderId,b)});const replacements=new Map(),keptIds=new Set([...latestBranchByFounder.values()].map(b=>b.id));db.branches.forEach(b=>{const kept=latestBranchByFounder.get(b.founderId);if(kept&&kept.id!==b.id)replacements.set(b.id,kept.id)});if(replacements.size){db.persons.forEach(p=>{if(replacements.has(p.branchId))p.branchId=replacements.get(p.branchId)});db.branches.forEach(b=>{if(replacements.has(b.parentBranchId))b.parentBranchId=replacements.get(b.parentBranchId)});db.branches=db.branches.filter(b=>!replacements.has(b.id)||keptIds.has(b.id))}}
function compactGeneratedBranchNames(){db.branches.filter(b=>b.founderId&&(b.order||b.startGeneration)).forEach(b=>{const founder=person(b.founderId);if(!founder)return;const parent=branch(b.parentBranchId),parentLabel=parent?(parent.order?`Nhánh thứ ${parent.order}`:(parent.name||parent.code||'Chi chưa xác định')):'Chi chưa xác định',order=Number(b.order)||Number(founder.branchOrder)||1,startGeneration=Number(founder.generationOverride)||generation(founder.id)||Number(b.startGeneration)||1,roomName=hasMultipleWives(founder.fatherId)?roomLabel(person(founder.motherId)):'',roomPart=roomName?` – ${roomName}`:'';b.name=`Nhánh thứ ${order}${roomPart} – thuộc ${parentLabel} – khởi từ đời thứ ${startGeneration}`;b.description=`Nhánh thứ ${order}${roomName?`, ${roomName}`:''}, thuộc ${parentLabel}, do ${founder.name} khởi đầu ở đời thứ ${startGeneration}`})}
const synchronizeLinkedDataCore=synchronizeLinkedData;synchronizeLinkedData=function(){deduplicateSavedProfiles();const result=synchronizeLinkedDataCore();compactGeneratedBranchNames();return result};
$('#clanForm').onsubmit=e=>{e.preventDefault();const form=e.currentTarget;const name=form.elements.clanName.value.trim();if(!name)return;save();const id='clan-'+uid();const next=emptyDb();next.clan.name=name;next.clan.origin=form.elements.origin.value.trim();workspaces.push({id,name});localStorage.setItem(`${STORE}.${id}`,JSON.stringify(next));activeWorkspaceId=id;db=next;save();form.closest('dialog').close();currentView='settings';renderAll();toast('Đã tạo gia phả mới')};
$('#personForm').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,fd=Object.fromEntries(new FormData(f)),before=JSON.stringify(db);if(!fd.name.trim()){toast('Vui lòng nhập họ và tên');return}if(fd.membership==='spouse'){fd.fatherId='';fd.motherId='';fd.roomMotherId='';fd.startsBranch='no';fd.branchOrder='';fd.descendantBranchCount='';fd.branchId='';}if(fd.roomMotherId)fd.motherId=fd.roomMotherId;const existing=person(fd.id);const father=person(fd.fatherId);if(father&&father.gender==='female'){toast('Cha phải là hồ sơ giới tính Nam');return}if(fd.startsBranch==='yes'&&(fd.gender!=='male'||fd.membership!=='lineage')){toast('Theo quy ước Nam hệ, chỉ thành viên nam nối dõi mới mở Nhánh');return}const now=new Date().toISOString(),base={...existing,...fd,id:fd.id||uid(),code:existing?.code||'NV-'+String(db.persons.length+1).padStart(4,'0'),avatar:avatarData,createdAt:existing?.createdAt||now,updatedAt:now};if(base.gender==='female'&&base.membership==='lineage')base.membership='clan';if(!base.branchId&&father?.branchId)base.branchId=father.branchId;if(base.startsBranch!=='yes'){const obsolete=db.branches.find(x=>x.founderId===base.id);if(obsolete){db.branches=db.branches.filter(x=>x.id!==obsolete.id);db.persons.forEach(x=>{if(x.branchId===obsolete.id)x.branchId=''})}}if(base.startsBranch==='yes'){const originBranch=db.branches.find(x=>x.founderId===base.id),parentBranchId=originBranch?.parentBranchId||base.branchId||father?.branchId||'',parentBranch=branch(parentBranchId),startGeneration=Number(base.generationOverride)||((generation(base.fatherId)||0)+1)||1;const order=Number(base.branchOrder)||db.branches.filter(x=>(x.parentBranchId||'')===parentBranchId).length+1;let b=originBranch;if(!b){b={id:uid(),code:'N'+String(db.branches.length+1).padStart(2,'0'),place:'',description:''};db.branches.push(b)}const parentName=parentBranch?.name||'Chi chưa xác định',roomName=hasMultipleWives(base.fatherId)?roomLabel(person(base.motherId)):'',roomPart=roomName?` – ${roomName}`:'';Object.assign(b,{name:`Nhánh thứ ${order}${roomPart} – thuộc ${parentName} – khởi từ đời thứ ${startGeneration}`,founderId:base.id,parentBranchId,order,startGeneration,description:`Nhánh thứ ${order}, ${roomName?roomName+', ':''}thuộc ${parentName}, do ${base.name} khởi đầu ở đời thứ ${startGeneration}`});base.branchId=b.id}if(existing)Object.assign(existing,base);else db.persons.push(base);synchronizeLinkedData();cleanupLegacyRootBranches();if(!save()){db=JSON.parse(before);return}f.closest('dialog').close();renderAll();toast(existing?'Đã cập nhật và đồng bộ hồ sơ':'Đã thêm và đồng bộ thành viên')};
$('#avatarInput').onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>1500000){toast('Ảnh quá lớn, vui lòng chọn ảnh dưới 1,5 MB');return}const r=new FileReader();r.onload=()=>{$('#avatarPreview').src=avatarData=r.result};r.readAsDataURL(file)};
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function marriageInfo(p){if(p.membership!=='spouse')return'';const mate=person(p.spouseOfId);const order=p.marriageOrder?`thứ ${p.marriageOrder}`:'';const role=p.gender==='female'?'Vợ':'Chồng';return `<div class="rule-hint"><b>Quan hệ hôn nhân:</b> ${role} ${order} của ${esc(mate?.name||'chưa chọn người phối ngẫu')}${p.marriageDate?` · Kết hôn: ${p.marriageDate}`:''}</div>`}
window.showPerson=function(id){const p=person(id),father=person(p.fatherId),mother=person(p.motherId);$('#detailContent').innerHTML=`<div class="profile"><div class="profile-top">${avatar(p)}<div><small>${p.code}</small><h2>${esc(p.name)}</h2><span class="chip ${p.gender}">${p.gender==='female'?'Nữ':'Nam'} · Đời ${generation(p.id)||'—'}</span></div></div><dl><div><dt>Ngày sinh – mất</dt><dd>${p.birth||'Chưa rõ'} ${p.death?'— '+p.death:''}</dd></div><div><dt>Chi · Nhánh</dt><dd>${esc(branch(p.branchId)?.name||'Chưa xếp')}</dd></div>${hasMultipleWives(p.fatherId)?`<div><dt>Phòng theo người mẹ</dt><dd>${esc(roomLabel(mother))}</dd></div>`:''}<div><dt>Nhánh con</dt><dd>${p.descendantBranchCount===''||p.descendantBranchCount==null?'Chưa khai':`Dự kiến ${p.descendantBranchCount} · Đã nhập ${childrenOf(p.id).filter(x=>x.gender==='male'&&isMain(x)).length} con trai nối dõi`}</dd></div>${p.gender==='male'&&p.membership==='lineage'?`<div><dt>Người vợ</dt><dd>${p.declaredWifeCount===''||p.declaredWifeCount==null?'Chưa khai số dự kiến':`Dự kiến ${p.declaredWifeCount}`} · Đã nhập ${wivesOf(p.id).length} hồ sơ</dd></div>`:''}<div><dt>Cha</dt><dd>${esc(father?.name||'Chưa rõ')}</dd></div><div><dt>Mẹ</dt><dd>${esc(mother?.name||'Chưa rõ')}</dd></div><div><dt>Quê quán</dt><dd>${esc(p.hometown||'—')}</dd></div><div><dt>Nghề nghiệp</dt><dd>${esc(p.occupation||'—')}</dd></div></dl>${marriageInfo(p)}${p.bio?`<p>${esc(p.bio)}</p>`:''}${p.gender==='female'&&db.clan.lineageMode==='patrilineal'?'<div class="rule-hint">Nhánh chính dừng tại thành viên nữ; hồ sơ vẫn được lưu đầy đủ.</div>':''}<div class="profile-actions"><button class="btn" onclick="$('#detailDialog').close()">Đóng</button><button class="btn primary" onclick="$('#detailDialog').close();openPersonForm('${p.id}')">Sửa hồ sơ</button></div></div>`;$('#detailDialog').showModal()}
window.addBranch=function(){const name=prompt('Tên Chi / Nhánh mới:');if(!name)return;db.branches.push({id:uid(),name,code:'C'+String(db.branches.length+1).padStart(2,'0'),place:'',description:'Chi nhánh mới'});save();renderAll();showView('branches');toast('Đã thêm chi nhánh')}
function addMedia(e){const f=e.target.files[0];if(!f)return;if(f.size>2000000)return toast('Tệp quá lớn cho bản local (tối đa 2 MB)');const r=new FileReader();r.onload=()=>{db.media.push({id:uid(),title:f.name,category:f.type.startsWith('image')?'Hình ảnh':'Tài liệu',data:r.result});save();renderMedia();toast('Đã lưu tư liệu')};r.readAsDataURL(f)}
const updateLineageFieldsWithChildRelation=updateLineageFields;updateLineageFields=function(){updateLineageFieldsWithChildRelation();const f=$('#personForm'),relation=f.elements.childRelation?.value||'biological';if(relation==='adopted'){f.elements.startsBranch.value='no';f.elements.descendantBranchCount.value='';$$('.branch-lineage-field,.descendant-count-field').forEach(x=>{x.hidden=true;x.style.display='none'});$('#singleChildHint').hidden=false;$('#singleChildHint').textContent='Con nuôi không nối dõi vẫn được ghi đầy đủ nhưng không tạo Nhánh Nam hệ. Nếu được dòng họ chính thức công nhận kế tự, hãy chọn “Con nuôi kế tự – được nối dõi”.'}};
const openPersonFormWithChildRelation=window.openPersonForm;window.openPersonForm=function(id=''){openPersonFormWithChildRelation(id);const f=$('#personForm'),p=person(id),field=f.elements.childRelation;field.value=p?.childRelation||field.value||'biological';field.onchange=updateLineageFields;updateLineageFields()};
const showPersonWithChildRelation=window.showPerson;window.showPerson=function(id){showPersonWithChildRelation(id);const p=person(id),labels={biological:'Con ruột',adopted:'Con nuôi – không nối dõi',adopted_heir:'Con nuôi kế tự – được dòng họ công nhận nối dõi'},dl=$('#detailContent dl');if(dl)dl.insertAdjacentHTML('afterbegin',`<div><dt>Quan hệ với cha mẹ</dt><dd>${labels[p.childRelation||'biological']}</dd></div>`)};
$('#personForm').addEventListener('submit',e=>{const f=e.currentTarget;if((f.elements.childRelation?.value||'biological')==='adopted'){f.elements.startsBranch.value='no';f.elements.descendantBranchCount.value=''}},true);
window.exportJSON=()=>download(`gia-pha-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(db,null,2));
window.exportCSV=()=>{const cols=['id','code','name','gender','birth','death','fatherId','motherId','childRelation','branchId','membership','occupation','hometown','birthplace','residence'];const cell=v=>'"'+String(v??'').replace(/"/g,'""')+'"';download('danh-sach-thanh-vien.csv','\ufeff'+[cols.join(','),...db.persons.map(p=>cols.map(c=>cell(p[c])).join(','))].join('\r\n'),'text/csv;charset=utf-8')};
window.exportGEDCOM=()=>{let s='0 HEAD\n1 GEDC\n2 VERS 7.0\n1 CHAR UTF-8\n1 SOUR GIA-PHA-VIET\n';db.persons.forEach((p,i)=>{p._ged=i+1;s+=`0 @I${i+1}@ INDI\n1 NAME ${p.name.replace(/^(\S+)\s+(.*)$/,'$2 /$1/')}\n1 SEX ${p.gender==='male'?'M':p.gender==='female'?'F':'U'}\n${p.birth?`1 BIRT\n2 DATE ${p.birth}\n`:''}${p.death?`1 DEAT\n2 DATE ${p.death}\n`:''}1 REFN ${p.code}\n1 NOTE GPV-MEMBERSHIP:${p.membership}\n`});const groups={};db.persons.filter(p=>p.fatherId||p.motherId).forEach(p=>{const k=(p.fatherId||'')+'|'+(p.motherId||'');(groups[k]??=[]).push(p)});Object.entries(groups).forEach(([k,kids],i)=>{const [fa,mo]=k.split('|');s+=`0 @F${i+1}@ FAM\n${fa?`1 HUSB @I${person(fa)._ged}@\n`:''}${mo?`1 WIFE @I${person(mo)._ged}@\n`:''}${kids.map(k=>`1 CHIL @I${k._ged}@`).join('\n')}\n`});s+='0 TRLR\n';download('gia-pha.ged',s,'text/plain;charset=utf-8')};
window.pickImport=()=>$('#restoreInput').click();
$('#restoreInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;const text=await f.text();try{if(f.name.toLowerCase().endsWith('.json')){const next=JSON.parse(text);if(!next.persons||!next.clan)throw Error();const clanCount=next.persons.filter(p=>p.membership==='lineage'||p.membership==='clan').length,relatedCount=next.persons.length-clanCount;if(confirm(`Khôi phục tổng cộng ${next.persons.length} hồ sơ?\n\n• ${clanCount} thành viên thuộc dòng họ\n• ${relatedCount} phối ngẫu/ngoại hệ\n\nDữ liệu hiện tại sẽ được thay thế.`)){db=next;save();renderAll();toast('Khôi phục thành công')}}else if(/\.csv$/i.test(f.name))importCSV(text);else importGEDCOM(text)}catch{toast('Tệp không hợp lệ hoặc không đúng định dạng')}e.target.value=''};
function importCSV(text){const lines=text.replace(/^\ufeff/,'').split(/\r?\n/).filter(Boolean);const parse=l=>{const a=[];let x='',q=false;for(let i=0;i<l.length;i++){if(l[i]==='"'&&l[i+1]==='"'){x+='"';i++}else if(l[i]==='"')q=!q;else if(l[i]===','&&!q){a.push(x);x=''}else x+=l[i]}a.push(x);return a};const h=parse(lines.shift());const rows=lines.map(l=>Object.fromEntries(parse(l).map((v,i)=>[h[i],v])));if(confirm(`Nhập thêm ${rows.length} hồ sơ từ CSV?`)){rows.forEach((p,i)=>db.persons.push({...p,id:db.persons.some(x=>x.id===p.id)?uid():p.id||uid(),code:p.code||'CSV-'+(i+1),createdAt:new Date().toISOString(),avatar:''}));save();renderAll();toast('Đã nhập CSV')}}
function importGEDCOM(text){const records=text.split(/\n(?=0 @I[^\n]+ INDI)/).slice(1);const added=[];records.forEach((r,i)=>{const name=(r.match(/\n1 NAME (.+)/)?.[1]||'Chưa rõ').replace(/([^/]*)\/([^/]*)\//,'$2 $1').trim();const sex=r.match(/\n1 SEX ([MF])/i)?.[1];const dates=[...r.matchAll(/\n1 (BIRT|DEAT)\n2 DATE (.+)/g)];added.push({id:uid(),code:'GED-'+String(i+1).padStart(4,'0'),name,gender:sex==='F'?'female':'male',birth:dates.find(x=>x[1]==='BIRT')?.[2]||'',death:dates.find(x=>x[1]==='DEAT')?.[2]||'',fatherId:'',motherId:'',branchId:'',membership:sex==='F'?'clan':'lineage',occupation:'',hometown:'',bio:'Nhập từ GEDCOM',avatar:'',createdAt:new Date().toISOString()})});if(!added.length)throw Error();if(confirm(`Nhập thêm ${added.length} cá nhân từ GEDCOM?`)){db.persons.push(...added);save();renderAll();toast('Đã nhập GEDCOM (quan hệ phức tạp cần rà soát)')}}
window.resetDemo=()=>{if(confirm('Tạo lại dữ liệu mẫu? Dữ liệu hiện tại sẽ bị thay thế. Hãy sao lưu trước.')){db=seed();save();renderAll();toast('Đã khôi phục dữ liệu mẫu')}};
$('#nav').onclick=e=>{const b=e.target.closest('button[data-view]');if(b)showView(b.dataset.view)};$('#quickAdd').onclick=()=>openPersonForm();$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');$('#globalSearch').oninput=e=>{showView('members');renderMembers(e.target.value)};$('#globalSearch').onkeydown=e=>{if(e.key==='Enter'){showView('members');renderMembers(e.target.value)}};$('#clanSwitcher').onchange=e=>switchWorkspace(e.target.value);$('#newClanBtn').onclick=createWorkspace;
const showPersonWithDates=window.showPerson;window.showPerson=function(id){showPersonWithDates(id);const p=person(id);if(!p)return;const cal=x=>x==='lunar'?'Âm lịch':x==='solar'?'Dương lịch':'Chưa rõ';const parts=[];if(p.birth)parts.push(`Sinh: ${esc(p.birth)} (${cal(p.birthCalendar||'solar')})`);if(p.death)parts.push(`Mất: ${esc(p.death)} (${cal(p.deathCalendar||'lunar')}${p.deathLeapMonth==='yes'?' · tháng nhuận':''})`);if(p.anniversary)parts.push(`Ngày giỗ: ${esc(p.anniversary)} (${cal(p.anniversaryCalendar||'lunar')})`);if(parts.length){const actions=$('#detailContent .profile-actions');actions?.insertAdjacentHTML('beforebegin',`<div class="rule-hint"><b>Ngày tháng:</b> ${parts.join(' · ')}</div>`)}}
const showPersonWithLocations=window.showPerson;window.showPerson=function(id){showPersonWithLocations(id);const p=person(id),actions=$('#detailContent .profile-actions');if(p&&actions){const modern=generation(p.id)>=10?` · Nơi sinh: ${esc(p.birthplace||'Chưa rõ')} · Trú quán: ${esc(p.residence||'Chưa rõ')}`:'';actions.insertAdjacentHTML('beforebegin',`<div class="rule-hint"><b>Địa danh:</b> Quê quán: ${esc(p.hometown||'Chưa rõ')}${modern}</div>`)}}
function cleanupLegacyRootBranches(){const invalidIds=new Set(db.branches.filter(b=>{const founder=person(b.founderId);return Number(b.startGeneration)===1||!!(founder&&generation(founder.id)===1&&String(b.name||'').startsWith('Nhánh thứ'))}).map(b=>b.id));if(invalidIds.size)db.branches=db.branches.filter(b=>!invalidIds.has(b.id));db.persons.forEach(p=>{const isRoot=generation(p.id)===1||Number(p.generationOverride)===1;if(invalidIds.has(p.branchId)||p.membership==='spouse'||isRoot)p.branchId='';if(p.membership==='spouse'||isRoot){p.startsBranch='no';p.branchOrder=''}})}
cleanupLegacyRootBranches();synchronizeLinkedData();renderAll();save();

// ===== Chọn vùng bằng chuột & Xuất PDF/Word cho Cây gia phả =====
function startAreaExport(){
  const wrap = document.querySelector('.tree-wrap');
  if(!wrap){ alert('Không tìm thấy cây gia phả để chọn vùng.'); return; }
  if(wrap.querySelector('.area-select-overlay')) return; // đang chọn rồi
  wrap.style.position = wrap.style.position || 'relative';
  const overlay = document.createElement('div');
  overlay.className = 'area-select-overlay';
  wrap.appendChild(overlay);
  let rectEl=null, startX=0, startY=0, dragging=false;

  function norm(x1,y1,x2,y2){return {x:Math.min(x1,x2),y:Math.min(y1,y2),w:Math.abs(x2-x1),h:Math.abs(y2-y1)};}
  function toContentXY(e){
    const r = wrap.getBoundingClientRect();
    return {x: e.clientX - r.left + wrap.scrollLeft, y: e.clientY - r.top + wrap.scrollTop};
  }
  function drawRect(sel){
    rectEl.style.left=(sel.x-wrap.scrollLeft)+'px';
    rectEl.style.top=(sel.y-wrap.scrollTop)+'px';
    rectEl.style.width=sel.w+'px';
    rectEl.style.height=sel.h+'px';
  }
  function onDown(e){
    dragging=true;
    const p=toContentXY(e); startX=p.x; startY=p.y;
    if(rectEl) rectEl.remove();
    rectEl=document.createElement('div'); rectEl.className='area-select-rect';
    overlay.appendChild(rectEl);
    drawRect(norm(startX,startY,startX,startY));
    e.preventDefault();
  }
  function onMove(e){
    if(!dragging) return;
    const p=toContentXY(e);
    drawRect(norm(startX,startY,p.x,p.y));
  }
  function onUp(e){
    if(!dragging) return;
    dragging=false;
    const p=toContentXY(e);
    const sel=norm(startX,startY,p.x,p.y);
    if(sel.w<15||sel.h<15){ cleanup(); return; }
    showToolbar(sel);
  }
  function showToolbar(sel){
    const bar=document.createElement('div');
    bar.className='area-select-toolbar';
    bar.style.left=(sel.x-wrap.scrollLeft)+'px';
    bar.style.top=(sel.y-wrap.scrollTop+sel.h+8)+'px';
    bar.innerHTML='<button class="btn small" data-act="pdf">⤓ Xuất PDF</button><button class="btn small" data-act="word">⤓ Xuất Word</button><button class="btn small" data-act="cancel">✕ Huỷ</button>';
    overlay.appendChild(bar);
    bar.querySelector('[data-act="pdf"]').onclick=()=>doExport(sel,'pdf',bar);
    bar.querySelector('[data-act="word"]').onclick=()=>doExport(sel,'word',bar);
    bar.querySelector('[data-act="cancel"]').onclick=cleanup;
  }
  function cleanup(){
    overlay.removeEventListener('mousedown', onDown);
    document.removeEventListener('mousemove', onMove);
    document.removeEventListener('mouseup', onUp);
    overlay.remove();
  }
  async function doExport(sel, kind, bar){
    bar.innerHTML='<span class="chip">Đang xử lý…</span>';
    overlay.style.display='none';
    try{
      const canvas = await html2canvas(wrap, {backgroundColor:'#f2ecdf', scale:2, useCORS:true});
      const scaleX = canvas.width / wrap.scrollWidth;
      const scaleY = canvas.height / wrap.scrollHeight;
      const crop = document.createElement('canvas');
      crop.width = Math.max(1, Math.round(sel.w*scaleX));
      crop.height = Math.max(1, Math.round(sel.h*scaleY));
      const ctx = crop.getContext('2d');
      ctx.drawImage(canvas, sel.x*scaleX, sel.y*scaleY, sel.w*scaleX, sel.h*scaleY, 0, 0, crop.width, crop.height);
      const dataUrl = crop.toDataURL('image/png');
      const clanName = (db.clan && db.clan.name ? db.clan.name : 'gia-pha').normalize('NFC').replace(/[\\/:*?"<>|]/g,'').trim().replace(/\s+/g,'-');
      if(kind==='pdf'){
        const { jsPDF } = window.jspdf;
        const orientation = crop.width>crop.height?'l':'p';
        const pdf = new jsPDF({orientation, unit:'px', format:[crop.width, crop.height]});
        pdf.addImage(dataUrl,'PNG',0,0,crop.width,crop.height);
        pdf.save(`cay-gia-pha-${clanName}.pdf`);
      }else{
        const html = `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0"><img src="${dataUrl}" style="max-width:100%"/></body></html>`;
        const blob = window.htmlDocx.asBlob(html, {orientation: crop.width>crop.height?'landscape':'portrait'});
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a'); a.href=url; a.download=`cay-gia-pha-${clanName}.docx`;
        document.body.appendChild(a); a.click(); a.remove();
        setTimeout(()=>URL.revokeObjectURL(url), 4000);
      }
    }catch(err){
      alert('Xuất file thất bại: '+(err&&err.message?err.message:err));
    }
    overlay.style.display='';
    cleanup();
  }

  overlay.addEventListener('mousedown', onDown);
  document.addEventListener('mousemove', onMove);
  document.addEventListener('mouseup', onUp);
}

// ===== Zoom in/out & Pan bằng chuột cho Cây gia phả =====
var treeZoomLevel = 1;
function applyTreeZoom(){
  const root = document.querySelector('.tree-root');
  const viewport = document.querySelector('.tree-zoom-viewport');
  if(root && viewport){
    root.style.transform = 'none';
    viewport.style.width = '';
    viewport.style.height = '';
    const baseW = root.scrollWidth, baseH = root.scrollHeight;
    if(baseW>0 && baseH>0){
      root.style.transform = `scale(${treeZoomLevel})`;
      root.style.transformOrigin = 'top left';
      viewport.style.width = (baseW*treeZoomLevel)+'px';
      viewport.style.height = (baseH*treeZoomLevel)+'px';
    }
  }
  const label = document.getElementById('zoomLabel');
  if(label) label.textContent = Math.round(treeZoomLevel*100)+'%';
}
function treeZoom(delta){
  treeZoomLevel = Math.min(2, Math.max(0.1, +(treeZoomLevel+delta).toFixed(2)));
  applyTreeZoom();
}
function treeZoomReset(){ treeZoomLevel = 1; applyTreeZoom(); }

var __treePanInit = false;
function ensureTreePanHandlers(){
  if(__treePanInit) return;
  __treePanInit = true;
  let panning=false, startX=0, startY=0, startLeft=0, startTop=0, moved=0, wrapEl=null;
  document.addEventListener('mousedown', e=>{
    const wrap = e.target.closest && e.target.closest('.tree-wrap');
    if(!wrap) return;
    if(e.target.closest('.area-select-overlay')) return; // đang ở chế độ chọn vùng, không pan
    if(e.button !== 0) return;
    panning=true; moved=0; wrapEl=wrap;
    startX=e.clientX; startY=e.clientY;
    startLeft=wrap.scrollLeft; startTop=wrap.scrollTop;
    wrap.classList.add('panning');
  });
  document.addEventListener('mousemove', e=>{
    if(!panning||!wrapEl) return;
    const dx=e.clientX-startX, dy=e.clientY-startY;
    moved=Math.max(moved, Math.abs(dx), Math.abs(dy));
    wrapEl.scrollLeft = startLeft - dx;
    wrapEl.scrollTop = startTop - dy;
  });
  document.addEventListener('mouseup', ()=>{
    if(!panning) return;
    panning=false;
    if(wrapEl){
      wrapEl.classList.remove('panning');
      if(moved>4){ const w=wrapEl; w.dataset.justDragged='1'; setTimeout(()=>{ delete w.dataset.justDragged; },50); }
    }
    wrapEl=null;
  });
  document.addEventListener('click', e=>{
    const wrap = e.target.closest && e.target.closest('.tree-wrap');
    if(wrap && wrap.dataset.justDragged){ e.stopPropagation(); e.preventDefault(); }
  }, true);
}
